# Generated by Django 3.1.1 on 2020-10-01 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0005_auto_20200929_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='zipcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
